spring.application.name=SpringSecurityExample

spring.security.user.name=himanshu
spring.security.user.password=password

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-boot-security-db
spring.datasource.username=postgres
spring.datasource.password=password
